name: ci for node app
on: [push]
jobs:
  gitlint-test-prettier-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: npm install
      - run: sudo apt-get install gitlint
      - run: gitlint
      - run: npm test
      - run: npx prettier --check src/
      - run: npx eslint src/
